### ISSUE TITLE
Mozilla UnifiedNlp Backend keeps crashing

### ISSUE THREAD

**Issue by derMart** [microg/UnifiedNlp#228]
**Describe the bug**
Mozilla UnifiedNlp Backend keeps crashing, logcat shows:
```
12-05 00:29:48.178 11925 11925 E AndroidRuntime: java.lang.RuntimeException: Unable to unbind to service org.microg.nlp.backend.ichnaea.BackendService@15321cf with Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.microg.nlp.backend.ichnaea cmp=org.microg.nlp.backend.ichnaea/.BackendService }: java.lang.IllegalStateException: Do not call onClose if not opened before
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4023)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:219)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1885)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Do not call onClose if not opened before
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at org.microg.nlp.api.AbstractBackendHelper.onClose(AbstractBackendHelper.java:47)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at org.microg.nlp.api.WiFiBackendHelper.onClose(WiFiBackendHelper.java:95)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at org.microg.nlp.api.HelperLocationBackendService.onClose(HelperLocationBackendService.java:64)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at org.microg.nlp.backend.ichnaea.BackendService.onClose(BackendService.java:153)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at org.microg.nlp.api.LocationBackendService.disconnect(LocationBackendService.java:80)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at org.microg.nlp.api.AbstractBackendService.onUnbind(AbstractBackendService.java:58)
12-05 00:29:48.178 11925 11925 E AndroidRuntime: 	at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4007)
```

**To Reproduce**

1. Open an App which tries to get location or open mozilla unifiednlp settings inside microg settings
4. See error after a while

**System**
Android Version: 10
Custom ROM: LineageOS with microg 17.1 (self compiled)

Mozilla UnifiedNlp Backend version: 1.4.0
MicroG version 0.2.22.212658

**Comment by JeffRockatansky** [comment]
Same issue on Oneplus 8 Pro (instantnoodlep, IN2023) with LineageOS-for-microg 18.1 (2022-04-04) and Mozilla Location Service (Mozilla UnifiedNlp Backend, `org.microg.nlp.backend.ichnaea`, 1.4.0)

**Comment by Estebiu** [comment]
Similar Issue here.
